---
org: encapsulate
domain_regex: ^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$
influxdb_dns: http://h1-finland-hub-monitor.crane-goldeye.ts.net:9122
ansible_port: 8192

architecture_map:
  x86_64: amd64
  aarch64: arm64

default_node_types:
  - validator
  - default

tmp_dir: /tmp

supra:
  validator:
    source_url: supraoracles/supra-{{ env }}-validator-node
  snapshot_endpoint_url: https://4ecc77f16aaa2e53317a19267e3034a4.r2.cloudflarestorage.com

aws:
  source_url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
