---
rpc_home_dir: /opt/{{ service_identifier }}

rpc_bin_dir: "{{ rpc_home_dir }}/bin"
rpc_log_dir: "{{ rpc_home_dir }}/log"
rpc_config_dir: "{{ rpc_home_dir }}/config"
rpc_archive_dir: "{{ rpc_config_dir }}/rpc_archive"
rpc_store_dir: "{{ rpc_config_dir }}/rpc_store"
rpc_ledger_dir: "{{ rpc_config_dir }}/rpc_ledger"
rpc_snapshot_dir: "{{ rpc_config_dir }}/snapshot"

rpc_directories:
  - "{{ rpc_home_dir }}"
  - "{{ rpc_bin_dir }}"
  - "{{ rpc_config_dir }}"
  - "{{ rpc_log_dir }}"
  - "{{ rpc_archive_dir }}"
  - "{{ rpc_store_dir }}"

rpc_archive_directories_and_files:
  - "{{ rpc_ledger_dir }}"
  - "{{ rpc_snapshot_dir }}"
  - "{{ rpc_archive_dir }}"
  - "{{ rpc_store_dir }}"
  - "{{ rpc_config_dir }}/latest_snapshot_rpc.zip"

rpc_config_file_path: "{{ rpc_bin_dir }}/{{ rpc_config_file_name }}"
rpc_ca_certificate_pem_file_path: "{{ rpc_config_dir }}/{{ rpc_ca_certificate_pem_file_name }}"
rpc_client_supra_certificate_pem_file_path: "{{ rpc_config_dir }}/{{ rpc_client_supra_certificate_pem_file_name }}"
rpc_client_supra_key_pem_file_path: "{{ rpc_config_dir }}/{{ rpc_client_supra_key_pem_file_name }}"
rpc_genesis_blob_file_path: "{{ rpc_config_dir }}/genesis_blob/genesis.blob"
rpc_supra_committees_json_file_path: "{{ rpc_config_dir }}/{{ rpc_supra_committees_json_file_name }}"
