---
- name: Snapshot sync Supra fullnode
  hosts: all
  become: true
  gather_facts: true
  vars:
    allowed_node_types: [fullnode]
  vars_files:
    - group_vars/all.yml
    - group_vars/{{ env }}.yml
  
  pre_tasks:
    - name: Setup environment
      when: type in allowed_node_types
      block:
        - name: Include environment setup tasks
          ansible.builtin.include_tasks: tasks/setup_environment.yml

  tasks:
    - name: Run fullnode snapshot sync role
      when: type in allowed_node_types
      block:
        - name: Include common handlers
          ansible.builtin.include_role:
            name: common
        - name: Include fullnode snapshot sync role
          ansible.builtin.include_role:
            name: fullnode_snapshot_sync
