---
- name: Setup Supra RPC node
  hosts: all
  become: true
  gather_facts: true
  vars:
    allowed_node_types: [rpc]
  vars_files:
    - group_vars/all.yml
    - group_vars/{{ env }}.yml
  tasks:
    - name: Setup environment and run rpc role
      when: type in allowed_node_types
      block:
        - name: Include environment setup tasks
          ansible.builtin.include_tasks: tasks/setup_environment.yml
        - name: Include common handlers
          ansible.builtin.include_role:
            name: common
        - name: Include prepare role
          ansible.builtin.include_role:
            name: prepare
        - name: Include rpc role
          ansible.builtin.include_role:
            name: rpc
