---
- name: Setup Promtail
  hosts: all
  become: true
  gather_facts: true
  vars:
    node_service_identifier: "{{ group_names[0] }}{{ '' if type in default_node_types else '-' + type }}"
    # because this promtail is being used for pushing to loki.services.supra.com, its service_identifier includes the node_service_identifier
    system_architecture: >-
      {%- if ansible_architecture == 'x86_64' -%}
        amd64
      {%- elif ansible_architecture == 'aarch64' -%}
        arm64
      {%- else -%}
        {{ ansible_architecture }}
      {%- endif -%}
  vars_files:
    - group_vars/all.yml
    - group_vars/default.yml
    - group_vars/vault.yml
    - group_vars/{{ env }}.yml

  tasks:
    - name: Set service_identifier
      set_fact:
        service_identifier: "{{ node_service_identifier }}-{{ promtail.service_identifier_suffix }}"

    - name: Include common handlers
      ansible.builtin.include_role:
        name: common
    - name: Include promtail role
      ansible.builtin.include_role:
        name: promtail
