---
- name: Download and Install Docker GPG key
  ansible.builtin.shell: |
    set -o pipefail
    wget -q -O - https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor | tee /etc/apt/keyrings/docker.gpg > /dev/null
  args:
    creates: /etc/apt/keyrings/docker.gpg
  changed_when: false

- name: Set proper permissions for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    owner: root
    group: root
    mode: "0644"

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Install Docker
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
