---
- name: Install Dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - coreutils
    - openssl
    - expect
    - ca-certificates
    - curl
    - gnupg
    - apt-transport-https
    - software-properties-common
    - unzip
    - rclone

- name: Install Docker
  ansible.builtin.import_tasks: install_docker.yml
