---
- name: Install Dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - coreutils
    - openssl
    - expect
    - python3-pip
    - ca-certificates
    - curl
    - apt-transport-https
    - software-properties-common
    - python3-toml
    - unzip

- name: Install Gcloud
  ansible.builtin.import_tasks: install_gcloud.yml

- name: Install Docker
  ansible.builtin.import_tasks: install_docker.yml
