---
- name: Include user creation task for supra fullnode
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ fullnode_home_dir }}"
    directories: "{{ fullnode_directories }}"

- name: Create Supra fullnode Docker container and copy binary
  vars:
    container_name: supra_fullnode
  block:
    - name: Create temporary Supra fullnode container for binary extraction
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ supra.fullnode.source_url }}:{{ supra.fullnode.version }}"
        state: present
        recreate: true

    - name: Copy Supra fullnode binary
      ansible.builtin.shell: >
        docker cp {{ container_name }}:/supra/rpc_node {{ fullnode_bin_dir }}/{{ service_identifier }}
      args:
        executable: /bin/bash
      register: copy_result
      changed_when: copy_result.rc == 0
      failed_when:
        - copy_result.rc != 0
        - "'No such container' in copy_result.stderr"

    - name: Ensure Supra fullnode binary has the correct permissions
      ansible.builtin.file:
        path: "{{ fullnode_bin_dir }}/{{ service_identifier }}"
        owner: root
        group: root
        mode: "0755"

  always:
    - name: Remove Supra fullnode container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

- name: Copy config.toml file
  ansible.builtin.template:
    src: "{{ env }}/config.toml.j2"
    dest: "{{ fullnode_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"

- name: Copy Supra fullnode certificates, keys and genesis
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  loop:
    - { src: "{{ env }}/certs/{{ fullnode_ca_certificate_file_name }}", dest: "{{ fullnode_ca_certificate_file_path }}" }
    - { src: "{{ env }}/certs/{{ fullnode_supra_certificate_file_name }}", dest: "{{ fullnode_supra_certificate_file_path }}" }
    - { src: "{{ env }}/certs/{{ fullnode_supra_key_file_name }}", dest: "{{ fullnode_supra_key_file_path }}" }
    - { src: "{{ env }}/{{ fullnode_supra_committees_file_name }}", dest: "{{ fullnode_config_dir }}" }
    - { src: "{{ env }}/{{ fullnode_genesis_blob_file_name }}", dest: "{{ fullnode_config_dir }}" }

- name: Copy supra fullnode env file
  ansible.builtin.template:
    src: "{{ env }}/normal_env_var"
    dest: "{{ fullnode_env_dir }}/{{ service_identifier }}.env"
    owner: root
    group: root
    mode: "0644"

- name: Copy supra-fullnode-node systemd service file
  ansible.builtin.template:
    src: "{{ env }}/supra-fullnode.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service

- name: Open supra fullnode node p2p port
  community.general.ufw:
    rule: allow
    port: "{{ supra.fullnode.ports.p2p_port }}"
    proto: tcp
    comment: Open p2p port for supra fullnode
