---
- name: Unzip the snapshot
  ansible.builtin.unarchive:
    src: "{{ supra.rpc.snapshot_url }}"
    dest: "{{ rpc_snapshot_sync_data_dir }}"
    remote_src: true

- name: Copy snapshot data into rpc store and archive
  ansible.builtin.shell: |
    cp {{ rpc_snapshot_sync_snapshot_dir }}/snapshot_*/store/* {{ rpc_snapshot_sync_store_dir }}
    cp {{ rpc_snapshot_sync_snapshot_dir }}/snapshot_*/archive/* {{ rpc_snapshot_sync_archive_dir }}
  args:
    executable: /bin/bash
  changed_when: false
  notify:
    - Reload service
    - Restart service
