---
snapshot_sync_home_dir: /opt/{{ service_identifier }}

snapshot_sync_data_dir: "{{ snapshot_sync_home_dir }}/data"

snapshot_sync_archive_dir: "{{ snapshot_sync_data_dir }}/rpc_archive"
snapshot_sync_store_dir: "{{ snapshot_sync_data_dir }}/rpc_store"
snapshot_sync_ledger_dir: "{{ snapshot_sync_data_dir }}/rpc_ledger"

snapshot_sync_smr_storage_dir: "{{ snapshot_sync_data_dir }}/smr_storage"
snapshot_sync_ledger_storage_dir: "{{ snapshot_sync_data_dir }}/ledger_storage"

snapshot_sync_directories:
  fullnode:
    - "{{ snapshot_sync_archive_dir }}"
    - "{{ snapshot_sync_store_dir }}"
    - "{{ snapshot_sync_ledger_dir }}"
  validator:
    - "{{ snapshot_sync_smr_storage_dir }}"
    - "{{ snapshot_sync_ledger_storage_dir }}"

snapshot_sync_rclone_config_content: |
  [cloudflare-r2]
  type = s3
  provider = Cloudflare
  access_key_id = 229502d7eedd0007640348c057869c90
  secret_access_key = 799d15f4fd23c57cd0f182f2ab85a19d885887d745e2391975bb27853e2db949
  region = auto
  endpoint = https://4ecc77f16aaa2e53317a19267e3034a4.r2.cloudflarestorage.com
  acl = private
  no_check_bucket = true
