---
- name: Unzip the snapshot
  ansible.builtin.unarchive:
    src: "{{ supra.validator.snapshot_url }}"
    dest: "{{ tmp_dir }}"
    remote_src: true

- name: Copy snapshot data into smr_storage
  ansible.builtin.shell: >
    cp {{ tmp_dir }}/snapshot/snapshot_*/store/* {{ validator_snapshot_sync_smr_storage_dir }}
  args:
    executable: /bin/bash
  changed_when: false
  notify:
    - Reload service
    - Restart service

- name: Clean up the temporary files in /tmp
  ansible.builtin.file:
    path: "{{ tmp_dir }}/snapshot"
    state: absent
