---
- name: Unzip the snapshot
  ansible.builtin.unarchive:
    src: "{{ supra.validator.snapshot_url }}"
    dest: "{{ validator_snapshot_sync_data_dir }}"
    remote_src: true

- name: Copy snapshot into smr_storage
  ansible.builtin.shell: >
    cp {{ validator_snapshot_sync_data_dir }}/snapshot/snapshot_*/store/* {{ validator_snapshot_sync_smr_storage_dir }}
  args:
    executable: /bin/bash
  changed_when: false
  notify:
    - Reload service
    - Restart service
