---
- name: Install Dependencies for gcloud
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - ca-certificates
    - curl
    - apt-transport-https
    - gnupg
    - curl

- name: Add Google Cloud SDK GPG key
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Download Google Cloud SDK GPG key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/cloud.google.gpg
    owner: root
    group: root
    mode: "0644"
    checksum: sha256:3ecc63922b7795eb23fdc449ff9396f9114cb3cf186d6f5b53ad4cc3ebfbb11f

- name: Add Google Cloud SDK repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.cloud.google.com/apt cloud-sdk main
    state: present
    filename: google-cloud-sdk

- name: Install gcloud-cli
  ansible.builtin.apt:
    name: google-cloud-cli
    state: present
    update_cache: true
