---
- name: Include user creation task for supra validator
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ validator_home_dir }}"
    directories: "{{ validator_directories }}"
    log_file_path: "{{ validator_log_file_path }}"

- name: Remove existing supra validator binary
  ansible.builtin.file:
    path: "{{ validator_bin_dir }}/{{ service_identifier }}"
    state: absent

- name: Create Supra Validator Docker container and copy binary
  block:
    - name: Create Supra validator Docker container
      community.docker.docker_container:
        name: supra_validator
        image: "{{ supra.validator.docker_image }}"
        state: started
        recreate: true
        volumes:
          - "{{ validator_home_dir }}:/supra/configs"
        env:
          SUPRA_HOME: /supra/configs
          SUPRA_LOG_DIR: /supra/configs/supra_node_logs
        network_mode: host
        detach: true
        interactive: true
        tty: true

    - name: Copy Supra validator binary
      ansible.builtin.shell: >
        docker cp supra_validator:/supra/supra {{ validator_bin_dir }}/{{ service_identifier }}
      args:
        executable: /bin/bash
      register: copy_result
      changed_when: copy_result.rc == 0
      failed_when:
        - copy_result.rc != 0
        - "'No such container' in copy_result.stderr"

  always:
    - name: Remove Supra validator container
      community.docker.docker_container:
        name: supra_validator
        state: absent
        force_kill: true

- name: Copy smr_settings.toml file
  ansible.builtin.template:
    src: "{{ env }}/smr_settings.toml.j2"
    dest: "{{ validator_smr_settings_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"

- name: Download validator certificates, key, and genesis config
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  loop:
    - { url: "{{ supra.validator.ca_certificate_pem_url }}", dest: "{{ validator_ca_certificate_pem_file_path }}" }
    - { url: "{{ supra.validator.server_supra_certificate_pem_url }}", dest: "{{ validator_server_supra_certificate_pem_file_path }}" }
    - { url: "{{ supra.validator.server_supra_key_pem_url }}", dest: "{{ validator_server_supra_key_pem_file_path }}" }
    - { url: "{{ supra.validator.genesis_configs_url }}", dest: "{{ validator_genesis_configs_json_file_path }}" }

- name: Copy supra-validator-node systemd service file
  ansible.builtin.template:
    src: "{{ env }}/supra.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service

- name: Open supra validator node p2p port
  community.general.ufw:
    rule: allow
    port: "{{ supra.validator.ports.p2p_port }}"
    proto: tcp
    comment: Open p2p port for supra validator
