---
fullnode_snapshot_sync_home_dir: /opt/{{ service_identifier }}

fullnode_snapshot_sync_data_dir: "{{ fullnode_snapshot_sync_home_dir }}/data"
fullnode_snapshot_sync_archive_dir: "{{ fullnode_snapshot_sync_data_dir }}/rpc_archive"
fullnode_snapshot_sync_store_dir: "{{ fullnode_snapshot_sync_data_dir }}/rpc_store"
