---
- name: Download AWS CLI v2 installer
  ansible.builtin.unarchive:
    src: "{{ aws.source_url }}"
    dest: "{{ tmp_dir }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Run AWS CLI install script
  ansible.builtin.command: ./aws/install --update
  args:
    chdir: /tmp
  register: aws_cli_install_result
  failed_when: aws_cli_install_result.rc != 0

- name: Clean up the AWS CLI installer folder in /tmp
  ansible.builtin.file:
    path: "{{ tmp_dir }}/aws"
    state: absent
