---
- name: Include user creation task for supra rpc
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ telegraf_home_dir }}"
    directories: "{{ telegraf_directories }}"
    log_file_path: "{{ telegraf_log_file_path }}"

- name: Download and unarchive the binary
  ansible.builtin.unarchive:
    src: "{{ telegraf.source_url }}"
    dest: "{{ tmp_dir }}"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy the binary file
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ telegraf_extracted_binary_path }}"
    dest: "{{ telegraf_bin_dir }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"

- name: Clean up the temporary files in /tmp
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ telegraf_extracted_binary_path }}"
    state: absent

- name: Copy telegraf config
  ansible.builtin.template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"

- name: Copy telegraf service file
  ansible.builtin.template:
    src: telegraf.service.j2
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
